### ISSUE TITLE
Disable Startup Sound(s)

### ISSUE THREAD

**Issue by CaptInsano** [fritz-smh/yi-hack#130]
Yi Cam 1 720p US model
Firmware: 1.8.6.1B_201604071151
Yi-Hack version: github.com/death2all110/yi-hack as of 1st Feb 2017

Is it possible to disable the startup music on yi-hack?

I have looked through the equip_test.sh and I saw these lines which I thought were relating to sounds only:

`### Let ppl hear that we start`
`/home/rmm "/home/hd1/test/voice/welcome.g726" 1`
`/home/rmm "/home/hd1/test/voice/wait.g726" 1`

So I tried to comment out the first line to match the following

`### Let ppl hear that we start`
`#/home/rmm "/home/hd1/test/voice/welcome.g726" 1`
`/home/rmm "/home/hd1/test/voice/wait.g726" 1`

While this **does** remove the startup music on booting the camera, the camera now does not successfully connect to wifi. Is there more to the /test/voice/*.g726 files than audio?

Is is possible for an option in yi-hack.cfg to remove the boot sounds? 
(Disable Music/Disable Wifi anouncements/Disable all sounds)

**Comment by death2all110** [comment]
**EDIT**
Can you create a new issue on [my repo](https://github.com/death2all110/yi-hack/issues) since you're using my fork? You can use [Gist by Github](https://gist.github.com/) to link me to the contents of the log file. 

~~Hey @CaptInsano can you post the contents of the log.txt file in the test directory on the SD card?~~

**Comment by CaptInsano** [comment]
Apologies,

I reformatted my SD card and retried the above with success

Issue Closed (probably user derp!)

Sorry again
