### ISSUE TITLE
Modify "Activity Zone"

### ISSUE THREAD

**Issue by anndrewww** [fritz-smh/yi-hack#149]
Has anyone had any luck modifying "etc/ui.conf" to change motion detection area/sensitivity/etc with "yi-hack" installed?

```
motion_mode=1
motion_left=428
motion_right=557
motion_top=0
motion_bottom=88
motion_resolution=5
motion_sensitivity=0
```
EDIT:

My working values in UI.conf:

```
motion_mode=1
motion_left=535
motion_right=677
motion_top=8    
motion_bottom=110
motion_resolution=5
motion_sensitivity=0
```

**Comment by utya1988** [comment]
I modified the email push string but not result.

**Comment by airdrummingfool** [comment]
I was able to modify the `motion_[left/right/top/bottom/sensitivity]` values using `vi` over telnet. Make sure that you `sync` and then `reboot` to apply the changes.

The resolution appears to be `1280x720`, so your max value for `motion_right` is `1279` and `motion_bottom` is `719`.

**Comment by anndrewww** [comment]
I was able to modify it as well, but it doesn't look like it has any effect.

**Comment by ujnatg** [comment]
could you please share more details about versions of firmware ? Fox example, I've no motion_* options predefined in ui.conf file

**Comment by notdone** [comment]
please share how to do that

**Comment by airdrummingfool** [comment]
@anndrewww As long as I sync and reboot after modifying the values (before connecting with the app), the app shows that the activity region has been moved. I'm able to trigger motion alerts in the newly-defined area, and alerts do not seem to trigger with motion in the old area.

@ujnatg I'm running `1.8.5.1N_201601071352`, which was the version I had to update to in order to be able to pair with the Yi Home app. I can confirm that they were not present when I was running `1.8.5.1M_201512011815`, the default version included in this hack (see #152, my PR for updating to the app-required firmware).

@notdone 
1. `telnet` into the camera
2. `vi /etc/ui.conf`, modify the values as you see fit (to skip to the motion section, you can search "motion_" by typing `/motion_` and hitting enter)
3. save and quit vi
4. `sync` to persist changes to flash memory
5. `reboot` to restart the Yi and apply the changes

**Comment by anndrewww** [comment]
@airdrummingfool 

Thanks, I'll try to test that out and see if I can get it working.

**Comment by notdone** [comment]
@airdrummingfool
oh my cam running 1.8.6.1B so dont have "motion_mod..." to modify the values.

**Comment by karepiu** [comment]
Have you been able to control cam being on/off using similar approach ?

**Comment by anndrewww** [comment]
Deleted
